crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(TemplateView.as_view(template_name='index.html')), name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('login/submit', views.submit_login, name='submit_login'),
    path('customer/', include('customer.urls'))
]

customer/urls.py
from django.urls import path
from .views import CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView

app_name = 'customer'

urlpatterns = [
    path("list/", CustomerListView.as_view(), name="customer-list"),
    path("", CustomerCreateView.as_view(), name="customer-create"),
    path("<int:id>/", CustomerUpdateView.as_view(), name="customer-update"),
    path("<int:id>/delete", CustomerDeleteView.as_view(), name="customer-delete")
]

core/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=80)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_phone(self):
        return f'({self.area_code}) {self.phone_number}'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_city(self):
        return f'{self.city} - {self.state}'

    def get_absolute_url(self):
        return reverse("customer:customer-update", kwargs={'id':self.id})

    def get_delete_url(self):
        return reverse("customer:customer-delete", kwargs={'id':self.id})

    class Meta:
        db_table = 'customer'

customer/forms.py
from django import forms
from .models import Customer

class DateInput(forms.DateInput):
    input_type = 'date'

class CustomerForm(forms.ModelForm):
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Sobrenome')
    email = forms.CharField(label='E-mail')
    birth_date = forms.DateField(label='Data Nascimento', widget=DateInput())
    area_code = forms.RegexField(label='DDD',
                                 regex=r"^\+?1?[0-9]{2}$",
                                # error_messages={"invalid":"DDD inválido"}
                                 )
    phone_number = forms.RegexField(label='Telefone',
                                 regex=r'^\+?1?[0-9]{9,15}$',
                                 error_messages={'invalid':'Telefone inválido'}
                                 )
    country = forms.CharField(label='País')
    state = forms.CharField(label='Estado')
    city = forms.CharField(label='Cidade')

    class Meta:
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "birth_date",
            "area_code",
            "phone_number",
            "country",
            "state",
            "city"
        )

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as app_login, logout as app_logout
from django.contrib import messages

def login(request):
    return render(request, 'login.html')

def submit_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            app_login(request, user)
            return redirect('index')
        else:
            messages.error(request, "Usuário/Senha Inválido, tente novamente")
    return redirect('login')

def logout(request):
    app_logout(request)
    return redirect('login')

customer/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Customer
from .forms import CustomerForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Q

class CustomerListView(ListView):
    template_name = 'customer/customer-list.html'
    paginate_by = 5
    model = Customer

    def get_queryset(self):
        name = self.request.GET.get('name')
        if name:
            object_list = self.model.objects.filter(
                Q(first_name__icontains=name) | Q(last_name__icontains=name)
            )
        else:
            object_list = self.model.objects.all()
        return object_list

class CustomerCreateView(CreateView):
    template_name = 'customer/customer.html'
    form_class = CustomerForm

    def form_invalid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")

class CustomerUpdateView(UpdateView):
    template_name = 'customer/customer.html'
    form_class = CustomerForm

    def get_object(self):
        id = self.kwargs.get('id')
        return get_object_or_404(Customer, id=id)

    def form_invalid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")

class CustomerDeleteView(DeleteView):

    def get_object(self):
        id = self.kwargs.get('id')
        return get_object_or_404(Customer, id=id)

    def get_success_url(self):
        return reverse("customer:customer-list")

core/templates/index.html
{% extends 'model-page.html' %}

{% block content %}
    <h1>TESTE</h1>
{% endblock %}

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" >

</head>

<body class="d-flex flex-column">
  <div class="sidenav">
         <div class="login-main-text">
            <h2>CRM<br>Sistema de Gestão de Clientes</h2>            
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form action="submit", method="POST">{% csrf_token %}
                  <div class="form-group">
                     <label>Usuário</label>
                     <input type="text" class="form-control" placeholder="Usuário" name="username">
                  </div>
                  <div class="form-group">
                     <label>Senha</label>
                     <input type="password" class="form-control" placeholder="Senha" name="password">
                  </div>
                  {% if messages %}
                      {% for message in messages %}
                          <div class="alert alert-danger">{{ message }}</div>
                      {% endfor %}

                  {% endif %}
                  <button type="submit" class="btn btn-black">Login</button>
                 
               </form>
            </div>
         </div>
      </div>
</body>
</html>

core/templates/model-footer.html
<div class="container text-center">
    <small>Desenvolvido por Gustavo Deckers</small>
</div>

core/templates/model-header.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">CRM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'customer:customer-list' %}">Clientes</a>
      </li>

      <!--
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li> -->
    </ul>
    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <a href="{% url 'logout' %}">Sair</a>
  </div>
</nav>

core/templates/model-page.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

</head>
<body class="d-flex flex-column">
    <header>
        {% include 'model-header.html' %}
    </header>
    <main class="content" style="margin-top: 3%">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>
    <footer class="py-4 bg-dark text-white-50">
        {% include 'model-footer.html' %}
    </footer>

</body>

<style>
    html, body {
    height: 100%
    }
    main {flex: 1 0 auto;}
    footer {
    flex_shirink: none;
    margin_top: 2em
    }
</style>
</html>

customer/templates/customer/customer-list.html
{% extends 'model-page.html' %}

{% block content %}
<h2>Clientes</h2>
<a href="{% url 'customer:customer-create' %}">
    <button class="btn btn-success mb-2" style="float:right; margin-bottom:5px">Adicionar</button>
</a>

<form>
    <div>
        <input type="text" class="form-control" name="name" placeholder="Busca por nome...">
    </div>
    <button class="btn btn-primary mt-2">Buscar</button>
</form>


<table class="table table-bordered mt-4">
  <thead>
    <tr>
        <th scope="col">Nome</th>
        <th scope="col">Cidade</th>
        <th scope="col">Telefone</th>
        <th scope="col">Email</th>
        <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for customer in customer_list %}
        <tr>
            <td><a href="{{ customer.get_absolute_url }}">{{ customer.get_full_name }}</a></td>
            <td>{{ customer.get_full_city }}</td>
            <td>{{ customer.get_full_phone }}</td>
            <td>{{ customer.email }}</td>
            <form method="post" action="{{ customer.get_delete_url }}">{% csrf_token %}
                <td><button type="submit" class="btn btn-danger">Excluir</button></td>
            </form>

        </tr>
    {% endfor %}
  </tbody>
</table>
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">Anterior</a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Anterior</a></li>
    {% endif %}

    {% for object in page_obj.paginator.page_range %}
        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter}}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Próximo</a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Próximo</a></li>
    {% endif %}
</ul>

{% endblock %}

customer/templates/customer/customer.html
{% extends 'model-page.html' %}
{% load crispy_forms_tags %}
{% block content %}

    {% if form.erros %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger"><strong>{{error|escape}}</strong></div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form method="post">{% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>


{% endblock %}